
int const MS_PER_FRAME = 50;

int const MIN_CAR_SPEED = 0;
int const MAX_CAR_SPEED = 140;
int const MIN_CAR_SPEED_FOR_TURN = 5;

int const POSITION_FOR_REMOVE_BOT = 60;
int const RECTANGLE_SYMBOL = 219;

int const WINDOW_WIDTH = 1000;
int const WINDOW_HEIGTH = 1200;

int const PLAYER_SPOWN_X = 26;
int const PLAYER_SPOWN_Y = 26;

int const MIN_SLEEP_VALUE = 0;

int const MAX_GAME_OBJECT = 6;

int const GAMEOVER_WINDOW_WIDTH = 500;
int const GAMEOVER_WINDOW_HEIGTH = 500;

int const ROAD_RIGTH_COORD = 43;
int const ROAD_TOP_COORD = 0;
int const ROAD_LEFT_COORD = 3;
int const ROAD_BOTTOM_COORD = 55;

int const START_STRIP_POSITION = 0;
int const STRIP_LENGTH = 4;

int const ROADWEY_COUNT = 2;

int const START_TIME_VALUE = 0;

int const WIDTH_ROAD_COLUMN = 5;

int const MAX_COLOR = 15;
int const FACTORY_COUNT = 4;

int const START_X_POSITION_FOR_BOT = -5;
int const MIN_SPEED_FOR_BOOT = 10;
int const MAX_SPEED_FOR_BOOT = 60;

enum Keys {
	KEYS_RIGHTKEY = 77,
	KEYS_LEFTKEY = 75,
	KEYS_UPKEY = 72,
	KEYS_DOWNKEY = 80,
	KEYS_ENTER = 13,
	KEYS_ESC = 27
};


enum Direction {
	DIRECTION_NORTH,
	DIRECTION_SOUTH,
	DIRECTION_WEST,
	DIRECTION_EAST
};


enum Color {
	COLOR_BLACK,
	COLOR_BLUE,
	COLOR_GREEN,
	COLOR_CYAN,
	COLOR_RED,
	COLOR_MAGENTA,
	COLOR_BROWN,
	COLOR_LIGHTGRAY,
	COLOR_DARKGRAY,
	COLOR_LIGHTBLUE,
	COLOR_LIGHTGREEN,
	COLOR_LIGHTCYAN,
	COLOR_LIGHTRED,
	COLOR_LIGHTMAGENTA,
	COLOR_YELLOW,
	COLOR_WHITE
};


enum CaseCollisionFactory {

	FACTORY_STANDART,
	FACTORY_HATCHBACK,
	FACTORY_SMART,
	FACTORY_SPORT
	
};